rootProject.name = "EasyMCApp"
enableFeaturePreview("VERSION_CATALOGS")
include(":app")
include(":novel:novel")
include(":novel:novel-api")
include(":common")
include(":tools:debug:crash")
include(":todo:todo-app")
include(":todo:todo-common-ui-resources")
include(":todo:todo-compose-components")
include(":todo:todo-ui-task")
include(":todo:todo-ui-addtask")
include(":todo:todo-ui-choose_date_time")
include(":todo:todo-data")
