// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search_history.proto

package top.mcwebsite.novel.data.local.datastore;

/**
 * Protobuf type {@code SearchHistory}
 */
public  final class SearchHistory extends
    com.google.protobuf.GeneratedMessageLite<
        SearchHistory, SearchHistory.Builder> implements
    // @@protoc_insertion_point(message_implements:SearchHistory)
    SearchHistoryOrBuilder {
  private SearchHistory() {
    text_ = "";
  }
  public static final int TEXT_FIELD_NUMBER = 1;
  private java.lang.String text_;
  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    return text_;
  }
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(text_);
  }
  /**
   * <code>string text = 1;</code>
   * @param value The text to set.
   */
  private void setText(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    text_ = value;
  }
  /**
   * <code>string text = 1;</code>
   */
  private void clearText() {
    
    text_ = getDefaultInstance().getText();
  }
  /**
   * <code>string text = 1;</code>
   * @param value The bytes for text to set.
   */
  private void setTextBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    text_ = value.toStringUtf8();
  }

  public static final int TIME_FIELD_NUMBER = 2;
  private long time_;
  /**
   * <code>int64 time = 2;</code>
   * @return The time.
   */
  @java.lang.Override
  public long getTime() {
    return time_;
  }
  /**
   * <code>int64 time = 2;</code>
   * @param value The time to set.
   */
  private void setTime(long value) {
    
    time_ = value;
  }
  /**
   * <code>int64 time = 2;</code>
   */
  private void clearTime() {
    
    time_ = 0L;
  }

  public static top.mcwebsite.novel.data.local.datastore.SearchHistory parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static top.mcwebsite.novel.data.local.datastore.SearchHistory parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static top.mcwebsite.novel.data.local.datastore.SearchHistory parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static top.mcwebsite.novel.data.local.datastore.SearchHistory parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static top.mcwebsite.novel.data.local.datastore.SearchHistory parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static top.mcwebsite.novel.data.local.datastore.SearchHistory parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static top.mcwebsite.novel.data.local.datastore.SearchHistory parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static top.mcwebsite.novel.data.local.datastore.SearchHistory parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static top.mcwebsite.novel.data.local.datastore.SearchHistory parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static top.mcwebsite.novel.data.local.datastore.SearchHistory parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static top.mcwebsite.novel.data.local.datastore.SearchHistory parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static top.mcwebsite.novel.data.local.datastore.SearchHistory parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(top.mcwebsite.novel.data.local.datastore.SearchHistory prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code SearchHistory}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        top.mcwebsite.novel.data.local.datastore.SearchHistory, Builder> implements
      // @@protoc_insertion_point(builder_implements:SearchHistory)
      top.mcwebsite.novel.data.local.datastore.SearchHistoryOrBuilder {
    // Construct using top.mcwebsite.novel.data.local.datastore.SearchHistory.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      return instance.getText();
    }
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      return instance.getTextBytes();
    }
    /**
     * <code>string text = 1;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      copyOnWrite();
      instance.setText(value);
      return this;
    }
    /**
     * <code>string text = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      copyOnWrite();
      instance.clearText();
      return this;
    }
    /**
     * <code>string text = 1;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTextBytes(value);
      return this;
    }

    /**
     * <code>int64 time = 2;</code>
     * @return The time.
     */
    @java.lang.Override
    public long getTime() {
      return instance.getTime();
    }
    /**
     * <code>int64 time = 2;</code>
     * @param value The time to set.
     * @return This builder for chaining.
     */
    public Builder setTime(long value) {
      copyOnWrite();
      instance.setTime(value);
      return this;
    }
    /**
     * <code>int64 time = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTime() {
      copyOnWrite();
      instance.clearTime();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:SearchHistory)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new top.mcwebsite.novel.data.local.datastore.SearchHistory();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "text_",
            "time_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0002" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<top.mcwebsite.novel.data.local.datastore.SearchHistory> parser = PARSER;
        if (parser == null) {
          synchronized (top.mcwebsite.novel.data.local.datastore.SearchHistory.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<top.mcwebsite.novel.data.local.datastore.SearchHistory>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:SearchHistory)
  private static final top.mcwebsite.novel.data.local.datastore.SearchHistory DEFAULT_INSTANCE;
  static {
    SearchHistory defaultInstance = new SearchHistory();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SearchHistory.class, defaultInstance);
  }

  public static top.mcwebsite.novel.data.local.datastore.SearchHistory getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SearchHistory> PARSER;

  public static com.google.protobuf.Parser<SearchHistory> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

