// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search_history.proto

package top.mcwebsite.novel.data.local.datastore;

public interface SearchHistoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchHistory)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>int64 time = 2;</code>
   * @return The time.
   */
  long getTime();
}
