// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search_history.proto

package top.mcwebsite.novel.data.local.datastore;

public interface SearchHistoriesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchHistories)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .SearchHistory histories = 1;</code>
   */
  java.util.List<top.mcwebsite.novel.data.local.datastore.SearchHistory> 
      getHistoriesList();
  /**
   * <code>repeated .SearchHistory histories = 1;</code>
   */
  top.mcwebsite.novel.data.local.datastore.SearchHistory getHistories(int index);
  /**
   * <code>repeated .SearchHistory histories = 1;</code>
   */
  int getHistoriesCount();
}
