// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search_history.proto

package top.mcwebsite.novel.data.local.serizlizer;

public final class SearchHistoryOuterClass {
  private SearchHistoryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
